/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borneomotor;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
//import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;
//import sun.swing.table.DefaultTableCellHeaderRenderer;



/**
 *
 * @author Ahmad
 */
public class fKategori extends javax.swing.JFrame {
String id_kategori;
DefaultTableModel model; 



    
    /**
     * Creates new form fKategori
     */
    public fKategori() {
        initComponents();
        setLocationRelativeTo(fKategori.this);
        KosongkanForm();
        BikinJudulKolom();
        //jPanel1.getPreferredSize("500","300");
        
    }
    
    private void lebarkolom(){
        TableColumn column;
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0); 
        column.setPreferredWidth(40);
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(300); 
        
        //rata tengah untuk judul kolom
//        DefaultTableCellHeaderRenderer tengahRenderer = new DefaultTableCellHeaderRenderer();
//        tengahRenderer.setHorizontalAlignment(DefaultTableCellHeaderRenderer.CENTER);
//        jTable1.getColumnModel().getColumn(0).setHeaderRenderer(tengahRenderer);
//        jTable1.getColumnModel().getColumn(1).setHeaderRenderer(tengahRenderer);
//        jTable1.getColumnModel().getColumn(2).setHeaderRenderer(tengahRenderer);
//        
       
        
        //rata tengah untuk kolom 0 (ID Kategori)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    }
    
    private void KosongkanForm() {
        jTextField1.setText("");
        jTextArea1.setText("");
        jTextField1.requestFocus();
        id_kategori="";
        
        
    }
    
    private void BikinJudulKolom(){
        Object[] judul_kolom={("ID"),("Nama Kategori"),("Keterangan")};
        DefaultTableModel model = new DefaultTableModel(null,judul_kolom);
        jTable1.setModel(model);
        model.getDataVector().removeAllElements();
       
        try 
        {
            koneksiDB.koneksi();
            koneksiDB.rs=koneksiDB.st.executeQuery("select * from kategori");
            while (koneksiDB.rs.next()) {
                Object[] data={koneksiDB.rs.getString("id_kategori"),
                                koneksiDB.rs.getString("nm_kategori"),
                                koneksiDB.rs.getString("keterangan")};
                model.addRow(data);
                }
            koneksiDB.putuskoneksi();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Menampilkan data gagal! Error: "+e);
        }
        lebarkolom();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Kategori");
        setMaximumSize(new java.awt.Dimension(520, 358));
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(jPanel1.getFont().deriveFont((jPanel1.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, 12));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel2.setText("Nama Kategori");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel3.setText("Keterangan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(jTextField1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jButton1.setMnemonic('s');
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(jButton1, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(480, 150));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(480, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 150));

        jTable1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(jScrollPane3, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/kategori3.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jButton2.setMnemonic('k');
        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel4.setText("Klik pada daftar untuk Edit Data.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextArea1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        if ("".equals(jTextField1.getText())) 
        {
            JOptionPane.showMessageDialog(null, "Nama Kategori tidak boleh kosong!");
            jTextField1.requestFocus(); 
            return;
        } 
        if ("".equals(jTextArea1.getText())) 
        {
            jTextArea1.setText("-"); 
            //return;
        }
        if (!"".equals(id_kategori))
        {   
            CekData2();
        }else{
            CekData(); 
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        
        
    }//GEN-LAST:event_formPropertyChange

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        
        id_kategori=jTable1.getModel().getValueAt(row,0).toString();
        jTextField1.setText(jTable1.getModel().getValueAt(row,1).toString());
        jTextArea1.setText(jTable1.getModel().getValueAt(row,2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void CekData2(){
    try {
        koneksiDB.koneksi();
        koneksiDB.rs=koneksiDB.st.executeQuery("select * from kategori "+
                                    "where nm_kategori='"+jTextField1.getText()+"' "+
                                    "and id_kategori<>'"+id_kategori+"'");
        //JOptionPane.showMessageDialog(null, "Hasil Query: "+rs.toString());
        if (koneksiDB.rs.next()) {
            koneksiDB.putuskoneksi();
            JOptionPane.showMessageDialog(null, "Nama Kategori "+jTextField1.getText()+" sudah ada. Masukkan nama lainnya.");
            jTextField1.requestFocus();
            
            }else {
                EditData();
                koneksiDB.putuskoneksi();
                KosongkanForm();
                BikinJudulKolom();
                //BikinJudul2();
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal melakukan cek data. Keterangan error: "+e);

        }
        
    }
    private void CekData(){
    try {
        koneksiDB.koneksi();
        koneksiDB.rs=koneksiDB.st.executeQuery("select * from kategori where nm_kategori='"+jTextField1.getText()+"'");
        //JOptionPane.showMessageDialog(null, "Hasil Query: "+rs.toString());
        if (koneksiDB.rs.next()) {
            koneksiDB.putuskoneksi();
            JOptionPane.showMessageDialog(null, "Nama Kategori "+jTextField1.getText()+" sudah ada. Masukkan nama lainnya.");
            jTextField1.requestFocus();
            
        }else {
            SimpanData();
            koneksiDB.putuskoneksi();
            KosongkanForm();
            BikinJudulKolom();
            //BikinJudul2();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal melakukan cek data. Keterangan error: "+e);
        
    }
        
    }
    
    private void EditData(){
    try {
        koneksiDB.koneksi();
        koneksiDB.st.executeUpdate("update kategori set nm_kategori='"+jTextField1.getText()+"',"+
                                    "keterangan='"+jTextArea1.getText()+"' "+
                                    "where id_kategori='"+id_kategori+"'");
        JOptionPane.showMessageDialog(null, "Data berhasil diedit...");
        KosongkanForm();
        //koneksiDB.putuskoneksi();
        BikinJudulKolom();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal diedit. Keterangan error: "+e);
        
    }
        
    }
    
    private void SimpanData(){
    try {
        //koneksi();
        koneksiDB.st.executeUpdate("insert into kategori (nm_kategori, keterangan) values ('"+jTextField1.getText()+"','"+jTextArea1.getText()+"')");
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan...");
        KosongkanForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan. Keterangan error: "+e);
        
    }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
