/*
 * Neng kene rusake. Ada 2 file untuk fUtama. Yaitu fUtama.frm dan fUtama.java
 * fUtama.frm berisi file semacam file xml untuk disain formnya, sedangkan fUtama.java adalah kode java aslinya.
 * fUtama.java berisi perintah-perintah yang harus dijalankan oleh fUtama.frm.
 */
package borneomotor;

import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad
 */
public class fUtama extends javax.swing.JFrame {
    public static Integer IdUserAktif;
    public static String NmUserAktif; 
    public static String MenuUser;
    //public static String NmForm;

    /**
     * Creates new form fUtama
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public fUtama() {
        initComponents();
        setLocationRelativeTo(this);
        setExtendedState(fUtama.MAXIMIZED_BOTH);
        IdUserAktif=0;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mLogin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mDataKategori = new javax.swing.JMenuItem();
        mDataSatuan = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mDataSparepart = new javax.swing.JMenuItem();
        mDataMekanik = new javax.swing.JMenuItem();
        mTransaksi = new javax.swing.JMenu();
        mTrService = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mUserManagement = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borneo Motor");
        setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/login2.png")); // NOI18N
        jButton1.setMnemonic('l');
        jButton1.setText("Login");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/kategori.png")); // NOI18N
        jButton2.setMnemonic('k');
        jButton2.setText("Kategori");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton2.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/satuan.png")); // NOI18N
        jButton3.setMnemonic('s');
        jButton3.setText("Satuan");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton3.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton3.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/sparepart.png")); // NOI18N
        jButton4.setMnemonic('i');
        jButton4.setText("Item");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton4.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton4.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/montir.png")); // NOI18N
        jButton5.setMnemonic('m');
        jButton5.setText("Mekanik");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton5.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton5.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/Muscle-Car-Mustang-GT-icon32.png")); // NOI18N
        jButton7.setMnemonic('o');
        jButton7.setText("Order");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton7.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton7.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/user.png")); // NOI18N
        jButton8.setMnemonic('u');
        jButton8.setText("User");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton8.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton8.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/keluar.png")); // NOI18N
        jButton9.setMnemonic('x');
        jButton9.setText("Exit");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMaximumSize(new java.awt.Dimension(70, 60));
        jButton9.setMinimumSize(new java.awt.Dimension(70, 60));
        jButton9.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jToolBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jToolBar2.setRollover(true);
        jToolBar2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel1.setText("www.borneo-media.com");
        jToolBar2.add(jLabel1);

        jMenu1.setMnemonic('s');
        jMenu1.setText("Sistem");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mLogin.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mLogin.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/login3.png")); // NOI18N
        mLogin.setMnemonic('l');
        mLogin.setText("Login");
        mLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mLogin);
        jMenu1.add(jSeparator1);

        mKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mKeluar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mKeluar.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/keluar2.png")); // NOI18N
        mKeluar.setMnemonic('k');
        mKeluar.setText("Keluar");
        mKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(mKeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('m');
        jMenu2.setText("Master Data");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mDataKategori.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        mDataKategori.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mDataKategori.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/kategori2.png")); // NOI18N
        mDataKategori.setMnemonic('k');
        mDataKategori.setText("Data Kategori");
        mDataKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDataKategoriActionPerformed(evt);
            }
        });
        jMenu2.add(mDataKategori);

        mDataSatuan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mDataSatuan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mDataSatuan.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/satuan2.png")); // NOI18N
        mDataSatuan.setMnemonic('s');
        mDataSatuan.setText("Data Satuan");
        mDataSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDataSatuanActionPerformed(evt);
            }
        });
        jMenu2.add(mDataSatuan);
        jMenu2.add(jSeparator2);

        mDataSparepart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mDataSparepart.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mDataSparepart.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/sparepart2.png")); // NOI18N
        mDataSparepart.setMnemonic('i');
        mDataSparepart.setText("Data Item");
        mDataSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDataSparepartActionPerformed(evt);
            }
        });
        jMenu2.add(mDataSparepart);

        mDataMekanik.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mDataMekanik.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mDataMekanik.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/montir2.png")); // NOI18N
        mDataMekanik.setMnemonic('m');
        mDataMekanik.setText("Data Mekanik");
        mDataMekanik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDataMekanikActionPerformed(evt);
            }
        });
        jMenu2.add(mDataMekanik);

        jMenuBar1.add(jMenu2);

        mTransaksi.setMnemonic('t');
        mTransaksi.setText("Transaksi");
        mTransaksi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mTrService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mTrService.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mTrService.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/Muscle-Car-Mustang-GT-icon16.png")); // NOI18N
        mTrService.setMnemonic('o');
        mTrService.setText("Transaksi Order");
        mTrService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTrServiceActionPerformed(evt);
            }
        });
        mTransaksi.add(mTrService);

        jMenuBar1.add(mTransaksi);

        jMenu4.setMnemonic('l');
        jMenu4.setText("Laporan");
        jMenu4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/report2.png")); // NOI18N
        jMenuItem1.setMnemonic('s');
        jMenuItem1.setText("Daftar Harga Sparepart/Jasa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/report3.png")); // NOI18N
        jMenuItem2.setMnemonic('p');
        jMenuItem2.setText("Laporan Pendapatan Harian");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('c');
        jMenu5.setText("Control Panel");
        jMenu5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mUserManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mUserManagement.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mUserManagement.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/user2.png")); // NOI18N
        mUserManagement.setMnemonic('u');
        mUserManagement.setText("User Management");
        mUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserManagementActionPerformed(evt);
            }
        });
        jMenu5.add(mUserManagement);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/ubahpassword.png")); // NOI18N
        jMenuItem4.setMnemonic('p');
        jMenuItem4.setText("Ubah Password");
        jMenu5.add(jMenuItem4);
        jMenu5.add(jSeparator9);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/settingDB.png")); // NOI18N
        jMenuItem5.setMnemonic('s');
        jMenuItem5.setText("Setting Database");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/resetdb.png")); // NOI18N
        jMenuItem6.setMnemonic('r');
        jMenuItem6.setText("Reset Database");
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu6.setMnemonic('b');
        jMenu6.setText("Bantuan");
        jMenu6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/hak-cipta.png")); // NOI18N
        jMenuItem7.setMnemonic('h');
        jMenuItem7.setText("Hak Cipta");
        jMenu6.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/registrasi16.png")); // NOI18N
        jMenuItem8.setMnemonic('r');
        jMenuItem8.setText("Registrasi Program");
        jMenu6.add(jMenuItem8);
        jMenu6.add(jSeparator10);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon("/media/ahmad/DATA2/BORNEO SOFTWARE/SOURCE CODE BDM/Borneo Motor/gambar/help16.png")); // NOI18N
        jMenuItem9.setMnemonic('p');
        jMenuItem9.setText("Panduan Program");
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jToolBar2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 340, Short.MAX_VALUE)
                .add(jToolBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginActionPerformed
        try{
            koneksiDB.koneksi();
            koneksiDB.rs=koneksiDB.st.executeQuery("select * from pengguna");
            if (koneksiDB.rs.next()){
                koneksiDB.putuskoneksi();
                String menu_login=fUtama.mLogin.getText();
                if ("Login".equals(menu_login)){
                    new fLogin().show();
                }else{
                    //JOptionPane.showMessageDialog(rootPane, "Anda yakin ingin Logout?",);
                    IdUserAktif=0;
                    NmUserAktif="";
                    mLogin.setText("Login");
                    jButton1.setText("Login");
                    jLabel1.setText("www.borneo-media.com");
                    
                    
                }
                
            }else{
                koneksiDB.putuskoneksi();
                new fUser().show();
            }
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);
            
        }
                
    }//GEN-LAST:event_mLoginActionPerformed

    private void mDataKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDataKategoriActionPerformed
        MenuUser="Data Kategori";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new fKategori().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }
            
 
  
    }//GEN-LAST:event_mDataKategoriActionPerformed

    private void mKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKeluarActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        System.exit(0);
        
                
    }//GEN-LAST:event_mKeluarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        mKeluar.doClick();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       mLogin.doClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserManagementActionPerformed
        MenuUser="User Management";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new fUser().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }
        
        
    }//GEN-LAST:event_mUserManagementActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        mUserManagement.doClick();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //this.enable(true);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        //this.enable(false);
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mDataKategori.doClick();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mDataSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDataSatuanActionPerformed
       
        MenuUser="Data Satuan";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new fSatuan().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }       
    }//GEN-LAST:event_mDataSatuanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mDataSatuan.doClick();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mDataSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDataSparepartActionPerformed

        
        MenuUser="Data Sparepart";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new fSparePart().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }       
    }//GEN-LAST:event_mDataSparepartActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mDataSparepart.doClick();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mDataMekanik.doClick();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mDataMekanikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDataMekanikActionPerformed
        
        
        MenuUser="Data Mekanik";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new fMekanik().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }            
    }//GEN-LAST:event_mDataMekanikActionPerformed

    private void mTrServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTrServiceActionPerformed
        
        
        MenuUser="Transaksi Order";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new fServices().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }                    
    }//GEN-LAST:event_mTrServiceActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mTrService.doClick();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MenuUser="Laporan Daftar Harga Sparepart/Jasa";
        if (IdUserAktif!=0){
             try{
                    koneksiDB.koneksi();
                    koneksiDB.rs=koneksiDB.st.executeQuery("select * from akses where id_user='"+IdUserAktif+"' and akses='"+MenuUser+"'");
                    if (koneksiDB.rs.next()){
                        koneksiDB.putuskoneksi();
                        MenuUser="";
                        new FReportHargaItem().show();

                    }else{
                        koneksiDB.putuskoneksi();
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini!");
                    }
            
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal! Error: "+e);

                }  
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum login, silahkan login dahulu.");
        }               
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mDataKategori;
    private javax.swing.JMenuItem mDataMekanik;
    private javax.swing.JMenuItem mDataSatuan;
    private javax.swing.JMenuItem mDataSparepart;
    private javax.swing.JMenuItem mKeluar;
    public static javax.swing.JMenuItem mLogin;
    private javax.swing.JMenuItem mTrService;
    private javax.swing.JMenu mTransaksi;
    private javax.swing.JMenuItem mUserManagement;
    // End of variables declaration//GEN-END:variables

    
    
}
